const fs = require("fs");
const { execSync } = require("child_process");

function loadDecisionFromOutput(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const a = raw.indexOf("{");
  const b = raw.lastIndexOf("}");
  if (a < 0 || b <= a) {
    throw new Error("无法从 AI 输出中提取决策 JSON");
  }
  const clean = raw.slice(a, b + 1).replace(/,\s*([\]}])/g, "$1");
  return JSON.parse(clean);
}

function getPRInfo() {
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath || !fs.existsSync(eventPath)) {
    return { number: null, title: "Unknown", author: "Unknown" };
  }
  const event = JSON.parse(fs.readFileSync(eventPath, "utf8"));
  return {
    number: event.pull_request?.number || null,
    title: event.pull_request?.title || "Unknown",
    author: event.pull_request?.user?.login || "Unknown",
  };
}

function postPRComment(prNumber, body) {
  if (!prNumber || !process.env.GH_TOKEN) {
    console.log("Skip PR comment (no PR number or token)");
    return;
  }
  const tmpFile = `pr-comment-${Date.now()}.md`;
  try {
    fs.writeFileSync(tmpFile, body, "utf8");
    execSync(
      `gh pr comment "${prNumber}" --body-file "${tmpFile}"`,
      { env: { ...process.env }, stdio: "pipe" }
    );
    console.log(`PR #${prNumber} comment posted`);
  } catch (err) {
    console.error("PR comment failed:", err.message);
  } finally {
    if (fs.existsSync(tmpFile)) fs.unlinkSync(tmpFile);
  }
}

function addPRLabel(prNumber, label) {
  if (!prNumber) return;
  try {
    execSync(`gh pr edit "${prNumber}" --add-label "${label}"`, {
      env: { ...process.env }, stdio: "pipe"
    });
  } catch {}
}

function mergePR(prNumber) {
  if (!prNumber) return;
  try {
    execSync(`gh pr merge "${prNumber}" --squash --auto`, {
      env: { ...process.env }, stdio: "pipe"
    });
    console.log(`PR #${prNumber} merged`);
  } catch (err) {
    console.error("Auto merge failed:", err.message);
  }
}

function formatComment(decision) {
  const emoji = { PASS: "✅", RETRY: "🔄", FAIL: "❌" };
  const text = {
    PASS: "全部通过，准备自动合并",
    RETRY: "需重试（AI 将尝试修复）",
    FAIL: "未通过，需人工介入",
  };

  let c = `## 🤖 AI Gate Review Result\n\n`;
  c += `**Decision**: ${emoji[decision.decision] || "❓"} **${decision.decision}** — ${text[decision.decision] || ""}\n\n`;
  c += `**Confidence**: ${((decision.confidence || 0) * 100).toFixed(0)}%`;

  if (decision.reviewScore != null) {
    const bar = decision.reviewScore >= 90 ? "🟢" : decision.reviewScore >= 70 ? "🟡" : "🔴";
    c += ` | **Review Score**: ${bar} ${decision.reviewScore}/100`;
  }
  c += `\n\n**Reason**: ${decision.reason}\n\n`;

  c += `### Stage Status\n| Stage | Status |\n|-------|--------|\n`;
  for (const [k, v] of Object.entries(decision.details || {})) {
    const icon = v === "success" ? "✅" : v === "failure" ? "❌" : "⏳";
    c += `| ${k} | ${icon} ${v} |\n`;
  }

  const findings = decision.findings || [];
  if (findings.length > 0) {
    const levels = { BLOCKER: "❌", CRITICAL: "🔴", WARNING: "⚠️", SUGGESTION: "💡" };
    c += `\n### Code Review Findings (${findings.length})\n`;
    c += `| Level | Category | File:Line | Message |\n`;
    c += `|-------|----------|-----------|--------|\n`;
    for (const f of findings) {
      c += `| ${levels[f.level] || "❓"} ${f.level} | ${f.category || "-"} | \`${f.file}:${f.line}\` | ${f.message} |\n`;
    }
  }

  if (decision.reviewSummary) {
    c += `\n### Review Summary\n${decision.reviewSummary}\n`;
  }

  const failures = decision.failures || [];
  if (failures.length > 0) {
    c += `\n### Issues Found\n`;
    for (const f of failures) {
      c += `- **${f.stage || f.file}**: ${f.message}\n`;
    }
  }

  if (decision.decision === "RETRY" && decision.retry_jobs?.length > 0) {
    c += `\n### Retry Plan\nRetry: ${decision.retry_jobs.join(", ")}\n`;
  }

  c += `\n---\n_Generated by OpenCode + OMO | ${new Date().toISOString()}_\n`;
  return c;
}

function main() {
  const filePath = process.argv[2] || "ai-output.log";

  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    process.exit(1);
  }

  const decision = loadDecisionFromOutput(filePath);
  const prInfo = getPRInfo();

  console.log(`Decision: ${decision.decision} (confidence: ${decision.confidence})`);
  console.log(`Reason: ${decision.reason}`);

  const comment = formatComment(decision);

  switch (decision.decision) {
    case "PASS":
      postPRComment(prInfo.number, comment);
      addPRLabel(prInfo.number, "ai-passed");
      mergePR(prInfo.number);
      break;
    case "RETRY":
      postPRComment(prInfo.number, comment);
      addPRLabel(prInfo.number, "ai-retry");
      for (const job of decision.retry_jobs || []) {
        console.log(`Retry job needed: ${job}`);
      }
      break;
    case "FAIL":
      postPRComment(prInfo.number, comment);
      addPRLabel(prInfo.number, "ai-failed");
      break;
    default:
      console.error(`Unknown decision: ${decision.decision}`);
      process.exit(1);
  }

  fs.writeFileSync("decision-result.json", JSON.stringify(decision, null, 2));
}

main();
