name: Test Outputs
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.step1.outputs.status }}
    steps:
      - id: step1
        run: echo "status=success" >> $GITHUB_OUTPUT
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.status }}
